qubitname = 'olivier_sample'


na_address = "TCPIP0::169.254.101.105::inst0::INSTR"
att_address = "TCPIP0::169.254.101.101::inst0::INSTR"
source_address = "GPIB0::2::INSTR"

source_port = 8

average_points = 999
center_frequency = 7350.9056e6
span_frequency = 5e6
npoints = 101
if_freq = 1e3
average_time = 60
attenuation = 34
volt_initial = -2.5
volt_final = -1.5
volt_step = 0.001
current_step_time = 0.1