qubitname = 'olivier_sample'


na_address = "TCPIP0::169.254.101.105::inst0::INSTR"
att_address = "TCPIP0::169.254.101.101::inst0::INSTR"

average_points = 999
center_frequency = 7350e6
span_frequency = 50e6
npoints = 251
if_freq = 1e3
average_time = 60

attenuation_initial = 0
attenuation_final = 40
attenuation_step = 5